### ISSUE TITLE
Original State

### ISSUE THREAD

**Issue by scaramonga** [leadustin/QIDI-up2date-english#7] opened 2024-05-01 22:48 UTC
Hello.

Can we have the steps to return machine to original state please?

**Comment by leadustin** [comment] 2024-05-02 06:10
I haven't tested it yet. But if you want to go back to the original state, you have to flash the original image from Qidi and then follow the steps to create the firmware. This should restore Klipper 0.10. Additionally I would copy the Moonraker and Klipper package from Qidi as I don't know how up to date the image is.

**Comment by NightHammer1000** [comment] 2024-05-02 06:30
I could give you an Guide on how to boot from an USB Drive and write the Image back to EMMC without actually having to buy an EMMC reader.

**Comment by leadustin** [comment] 2024-05-02 12:30
> I could give you an Guide on how to boot from an USB Drive and write the Image back to EMMC without actually having to buy an EMMC reader.

I am very interested in this guide. If you could make it available, that would be great.

**Comment by scaramonga** [comment] 2024-05-02 21:39
> I haven't tested it yet. But if you want to go back to the original state, you have to flash the original image from Qidi and then follow the steps to create the firmware. This should restore Klipper 0.10. Additionally I would copy the Moonraker and Klipper package from Qidi as I don't know how up to date the image is.

Thanks.  I don't think the mainboard/EMMC will be a problem, but how to restore print head might be?, unless Qidi's firmware flashes this also?

**Comment by leadustin** [comment] 2024-05-03 07:18
> > I haven't tested it yet. But if you want to go back to the original state, you have to flash the original image from Qidi and then follow the steps to create the firmware. This should restore Klipper 0.10. Additionally I would copy the Moonraker and Klipper package from Qidi as I don't know how up to date the image is.
> 
> Thanks. I don't think the mainboard/EMMC will be a problem, but how to restore print head might be?, unless Qidi's firmware flashes this also?

You use my guide to flash the firmware. It describes how to flash the print head. This is the part with the two buttons.

**Comment by scaramonga** [comment] 2024-05-03 07:50
> You use my guide to flash the firmware. It describes how to flash the print head. This is the part with the two buttons.

Yes, that is for Katapult, surely the way Qidi had the head setup is different?, otherwise, what would be the point in flashing it at all?

**Comment by leadustin** [comment] 2024-05-03 08:22
> > You use my guide to flash the firmware. It describes how to flash the print head. This is the part with the two buttons.
> 
> Yes, that is for Katapult, surely the way Qidi had the head setup is different?, otherwise, what would be the point in flashing it at all?

Catapult is intended to flash the print head without pressing the two buttons during future updates. You can also go the way Qidi describes. Does not matter.

**Comment by scaramonga** [comment] 2024-05-04 01:46
Qidi describes nothing, as regards the print head.  No matter, I have another board for it on the way.  This should get it back to square one, hopefully.

This 'update', while all good in intentions, does nothing but render the printer in a state of uncertainty.

Camera refuses to work, period!, and believe me, I've tried everything to get it to do so.  (Video0/1/2/3 etc., Crowsnest, configs, logs etc.)  Mainsail or Fluidd, both the same.

'Z' offset and other settings do not save once printer is switched off, or sometimes they do?, but it's dammed irritating regardless.

Connection to printer randomly lost, resulting in me having to input these details back into 'Orca' every so often, then having to do the above again.

Failed prints galore, despite tweaking any settings.  Weird movements of control system via KS, only at times, and several crashes into bed and surroundings with the print head.

Listen, I'm not blaming you, as it was a great idea to do this, and I'm the one to blame for making the move in doing so.

I will try and start to recover system on Monday.  Got a few hints and files to try, so hopefully I can get it back to how it was, if not?, we move on ;), and I'll replace the head board when I receive, which should do it regardless.

**Comment by leadustin** [comment] 2024-05-05 20:50
> Qidi describes nothing, as regards the print head

https://github.com/QIDITECH/QIDI_PLUS3/issues/27#issuecomment-2073932891
Jump to step "for extruder MCU"

> This 'update', while all good in intentions, does nothing but render the printer in a state of uncertainty.

I don't understand your problems there! The guide is exactly how I updated my printer. 
I can't reproduce any of the errors you mentioned


> Camera refuses to work, period!, and believe me, I've tried everything to get it to do so. (Video0/1/2/3 etc., Crowsnest, configs, logs etc.) Mainsail or Fluidd, both the same.

Have you checked in the SSH console with `lsusb` whether your camera is recognised at all? If it is a driver problem, you will also need to install the appropriate driver for the device
![grafik](https://github.com/leadustin/QIDI-up2date-english/assets/155164500/69b272ac-431d-4881-ac42-507c3024cf72)



> 'Z' offset and other settings do not save once printer is switched off, or sometimes they do?, but it's dammed irritating regardless.

Z-Offset and all other settings made in Mainsail are definitely saved in printer.cfg. Changes made via Klipperscreen are also saved correctly.
I also recommend shutting down the printer via Mainsail in the host control at the end of printing to prevent data loss. So don't just switch it off at the switch

> Connection to printer randomly lost, resulting in me having to input these details back into 'Orca' every so often, then having to do the above again.

I can't understand that either. Possibly call up the web interface directly in the browser. It is possible that your network is causing problems. Have you assigned a fixed IP to the printer?


> Failed prints galore, despite tweaking any settings. Weird movements of control system via KS, only at times, and several crashes into bed and surroundings with the print head.

Can you provide me with the complete config folder? And which printer is it exactly? MAX3-BL or probe etc.? With the printer.cfg etc. provided by me, there can be no bed crashes unless you have configured something completely different.


> If you decided to replace the EMMC with the 32G version anyway, like myself, and kept the original 8G variant (untouched), and think you can put that back, then flash latest firmware, forget it. System will be bricked.

Even with the original EMMC, everything that was flashed to Klipper 0.12 MUST be flashed to the original Klipper from Qidi. The instructions on how to flash can be found in my guide or at the beginning of this post. Therefore again: First install the original system image. Then create and flash the firmware for the STM chip and the print head based on the Qidi clipper.

**Comment by scaramonga** [comment] 2024-05-05 21:35
Hey, thx for the extra info, more so regarding print head.  Much appreciated :)  Will get on to this tomorrow.  Don't know why it's not working properly on my system?, but it is what it is.

Camera is the one from Qidi, no drivers required, at least none were when I installed it with original setup/firmware.

X-PLUS 3 is my printer.

Many thanks again.

**Comment by scaramonga** [comment] 2024-05-07 03:56
All went poorly.

To flash the print head, we need to put it into "DFU mode", but the other guide says to just hold 'BOOT' button?  Which is it??

Motherboard and EMMC fine, as expected, but print head, no way!! :(  Be prepared to have another print head board if doing this mod, as that MCU ain't gonna return to stock when flashed, no matter who says.

**Comment by leadustin** [comment] 2024-05-07 08:26
I have opened an issue in the Qidi Github.
[This is the official answer regarding flashing of the toolhead](https://github.com/QIDITECH/QIDI_MAX3/issues/47#issuecomment-2097547875)
Did you also remove all USB devices like camera and USB sticks?

**Comment by scaramonga** [comment] 2024-05-07 21:53
> I have opened an issue in the Qidi Github. [This is the official answer regarding flashing of the toolhead](https://github.com/QIDITECH/QIDI_MAX3/issues/47#issuecomment-2097547875) Did you also remove all USB devices like camera and USB sticks?

Only thing connected to mainboard is an Ethernet cable.  Even the Wi-Fi/Bluetooth dongle is removed.

**Comment by scaramonga** [comment] 2024-05-12 03:27
You can mark as fixed.

**Closed** 2024-05-12 10:45 UTC
